/*
*
*
*
*
*
*
*
*
*
*
*
*       DO NOT EDIT THIS FILE
*       For FCC testing purposes!
*
*
*
*
*
*
*
*
*
*
*
*/

'use strict';

var fs = require('fs');
var path = require('path');
var runner = require('../test-runner');

module.exports = function (app) {

  app.route('/_api/app-info')
    .get(function (req, res) {
      res.json({ version: '0.0.1' });
    });

  app.route('/_api/tests')
    .get(function (req, res) {
      fs.readdir(path.join(__dirname, '../tests'), function (err, files) {
        if (err) return res.json({ error: err });

        let testFile = files.filter(f => f.toLowerCase() === '2_functional-tests.js')[0];
        if (!testFile) return res.json({ error: 'No tests found' });

        fs.readFile(path.join(__dirname, '../tests', testFile), function (err, data) {
          if (err) return res.json({ error: err });
          res.type('txt').send(data.toString());
        });
      });
    });

};